### ISSUE TITLE
PostGIS

### ISSUE THREAD

**Issue by CaioBianchi** [evilmartians/terraforming-rails#11]
How would one go about including PostGIS with this setup?

I tried adding: 
```
postgresql-11-pgrouting
postgresql-11-pgrouting-scripts
postgresql-11-postgis-2.5
postgresql-11-postgis-2.5-scripts
```

To both my `Aptfile` and my `Dockerfile` (in 2 different tries), none of which worked.
IIRC, Postgres now carries the PostGIS package in its apt repository. But yet I'm getting `Unable to locate package postgresql-11-postgis-2.5` when I run `docker-compose build`.

Any thoughts?

**Comment by CaioBianchi** [comment]
Temporary solution was to use: [mdillon's PostGIS image](https://hub.docker.com/r/mdillon/postgis) for now.

**Comment by palkan** [comment]
Which Ruby version do you use?

Probably, it uses an Ubuntu image different from `stretch`, so we need to update this command to the corresponding Debian version:

```
deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main
```

**Comment by CaioBianchi** [comment]
I'm using Ruby `2.6.4`

>  ```echo 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main' $PG_MAJOR > /etc/apt/sources.list.d/pgdg.list```

This is what I'm using, still doesn't work.
I tried with `bionic`, `eaon` etc... none of which worked.

**Comment by sponomarev** [comment]
It should be there
http://apt.postgresql.org/pub/repos/apt/pool/main/p/postgis/
http://apt.postgresql.org/pub/repos/apt/pool/main/p/pgrouting/

**Comment by CaioBianchi** [comment]
Yeah. 😢  but it can't find it for some reason. 
Try adding this to your `Aptfile`:
```
postgresql-11-pgrouting
postgresql-11-pgrouting-scripts
postgresql-11-postgis-2.5
postgresql-11-postgis-2.5-scripts
```

**Comment by sponomarev** [comment]
@CaioBianchi Correct Debian release name for the latest Ruby image is `buster`. I've tried it locally and it finds the packages you want. 

Anyway, I just want to warn you that it would be better to run PG with Postgis as a dependent service using the proper docker image.

**Comment by sponomarev** [comment]
In general, it won't be an issue after  #12 merging.

**Comment by CaioBianchi** [comment]
Awesome @sponomarev! Thank you for the PR and your comments!
Yeah, I've been back and forth on whether I should run Pg+Postgis as a dependent service or install as a standalone package as mentioned above.
