### ISSUE TITLE
`No such service: backend` On `dip provision`

### ISSUE THREAD

**Issue by bekicot** [evilmartians/terraforming-rails#16]
When I run
`dip provision`
on dockerdev example,

I get
`No such service: backend`

If this is a valid issue, i would love to fix it. please guide as this is could be my first docker related repo pull request.

**Comment by LimeBlast** [comment]
I was just about to post exactly the same issue - I've updated all instances of `backend` to `runner` within the `dip.yml` file and that seems to work.

**Comment by palkan** [comment]
@bekicot Thanks for catching!

> If this is a valid issue, i would love to fix it. please guide as this is could be my first docker related repo pull request.

Oops, sorry, didn't notice this and already fixed 🙂
