### ISSUE TITLE
No Web Server

### ISSUE THREAD

**Issue by gkirill** [evilmartians/terraforming-rails#17]
Is there are a reason why an web server is not used for this setup? E.g. Nginx. How are you handling this in production?

**Comment by Envek** [comment]
This repository primarily contains recipes suitable for enhancing the development environment and easing code refactoring.

In the majority of our projects Nginx is being used (either as a standalone installation or as Kubernetes' Ingress controller), but production setup may differ wildly depending on used application servers and hosting platforms, so it is hard to give some kind of common advice for everyone. 

But if you want to add some best practices about production setup, pull requests are welcome!

**Comment by palkan** [comment]
Thanks @Envek!
