### ISSUE TITLE
installing the requested version of bundler

### ISSUE THREAD

**Issue by jnicho02** [evilmartians/terraforming-rails#23]
I've inherited a Rails 4.2 project, meaning that it won't work with bundler 2+

My build seems determined to use bundler 2.1.2....are you certain that the gem install of a specific version works. It might install, but continue to use 2.1.2 as 'default'.

I changed the Dockerfile to uninstall bundler before re-installing, and to define my new one as default. It didn't quite work for 1.16.0, but has for 1.17.2
```sh
RUN gem update --system && \
    gem uninstall bundler && \
    gem install bundler:$BUNDLER_VERSION --default
```

I will of course upgrade Rails ASAP

**Comment by palkan** [comment]
> I changed the Dockerfile to uninstall bundler before re-installing, and to define my new one as default

Looks great. Would you like to propose a PR with this change?

**Comment by jnicho02** [comment]
Absolutely.

It is not perfect yet, but it is better. I will try to improve it first
