### ISSUE TITLE
Update to latest docker compose

### ISSUE THREAD

**Issue by Bertg** [evilmartians/terraforming-rails#25]
It would be nice if the example is updated to latest docker compose version. 

However, this would require the ```condition``` part of the ```depends_on``` statements to be removed, as these are no longer supported. 

I think it is a good idea to indicate to the reader that healthcares checks are a responsibility of the application (per the docker docs: https://docs.docker.com/compose/startup-order/) and should the be handled there.

I would NOT replace it with a similar solution using a "wait for" hack or something similar.

**Comment by palkan** [comment]
> It would be nice if the example is updated to latest docker compose version.

Version 2 is used intentionally (we had v3 previously, you can find it [here](https://github.com/evilmartians/terraforming-rails/blob/d5f470e2afa498578be2ced0d68c4c83c2f271fa/examples/dockerdev/docker-compose.yml). It suites local development more than v3. See also https://github.com/docker/docker.github.io/pull/7593.

**Comment by Bertg** [comment]
Oh man. That is a great piece of information right there, I was completely unaware.

I posted this issue, as I was trying to follow your recommendations locally and got in trouble with the ```condition``` parts.

I'm fairly new to docker and had no idea about the v2 vs v3 differences and assumed "newer is better'. I imagine that more people might run into this. 

Maybe it could be useful to put a note about that explicit choice in the readme or the original blog post?

**Comment by palkan** [comment]
Added a side note to the post: https://evilmartians.com/chronicles/ruby-on-whales-docker-for-ruby-rails-development
