### ISSUE TITLE
Docker-compose - wrong path to .psqlrc in postgres service? 

### ISSUE THREAD

**Issue by lauer** [evilmartians/terraforming-rails#3]
Is there a reason why the `.psqlrc` in postgres service, points to the root dir, and not the `.dockerdev/.psqlrc` as it does in `backend` service

https://github.com/evilmartians/terraforming-rails/blob/657b27a813396ac8470aa0088a30ed15e5c1f78b/examples/dockerdev/docker-compose.yml#L64

**Comment by palkan** [comment]
Thanks for catching this!
