### ISSUE TITLE
Dockerfile in article has the wrong path for Aptfile

### ISSUE THREAD

**Issue by j-manu** [evilmartians/terraforming-rails#33]
Dockerfile in article (https://evilmartians.com/chronicles/ruby-on-whales-docker-for-ruby-rails-development) has

![image](https://user-images.githubusercontent.com/72501/108173964-d4ed1280-7124-11eb-871f-69845a18be9b.png)

but it should be `COPY Aptfile /tmp/Aptfile`. The dockerfile in this repo is correct.

**Comment by Envek** [comment]
Version 1.1.2 of [the blog post](https://evilmartians.com/chronicles/ruby-on-whales-docker-for-ruby-rails-development) has been released. Thank you for noticing!
