### ISSUE TITLE
Why not Alpine?

### ISSUE THREAD

**Issue by jandudulski** [evilmartians/terraforming-rails#44]
I wonder if there is any specific reasoning why did you use Debian's buster (btw there is [bullseye](https://wiki.debian.org/DebianBullseye) already for some time) instead of alpine? Is it just a matter of personal preference?

And by the way, thank you a lot for this guide :pray:

**Comment by palkan** [comment]
The main reason for using Debian and not Alpine for development is to provide a more flexible and familiar development environment, so you can login into an SSH session, open an editor within a container if necessary, add additional dev-only tools, etc. I literally run `apt-get install xyz` from time to time within a container for a one-off task. 

>  there is bullseye already for some time

Yeah, we should probably upgrade)

**Comment by jandudulski** [comment]
Thanks for explanation :beers:
