### ISSUE TITLE
Why don't you use docker-sync for better performance?

### ISSUE THREAD

**Issue by denikus** [evilmartians/terraforming-rails#48]
As I see, you don't use docker-sync for better file sync performance on macos. Or something like mutagen. Why?

**Comment by elalemanyo** [comment]
This is a very good question. Although I like using docker, the performance on macOS is really bad. I didn't use docker-sync or mutagen because the configuration became very complicated 🙈 Is it worth the complexity?

BTW: I have high hopes for [this](https://github.com/docker/roadmap/issues/7).

**Comment by palkan** [comment]
A proper use of volumes and `:cached/:delegated` (and gRPC FUSE in the latest Docker version) are well enough and pretty stable; adding additional layer (and maintainability burden) as docker-sync doesn't worth it.

And, yes, we believe and bright future and prefer not to rely on third-parties when possible.
