### ISSUE TITLE
GLIBC_2.29 not found using ruby 3.1.0

### ISSUE THREAD

**Issue by elalemanyo** [evilmartians/terraforming-rails#51]
Hi,
I am trying to update ruby (v.3.1.0), it seems that `Nokogiri` is missing `GLIBC_2.29`. Is anyone having the same issue?

This is the error that I am getting:

```
/lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/bundle/gems/nokogiri-1.13.0-aarch64-linux/lib/nokogiri/3.1/nokogiri.so) - /usr/local/bundle/gems/nokogiri-1.13.0-aarch64-linux/lib/nokogiri/3.1/nokogiri.so
```

Any help will be welcome 😃
Thanks

**Comment by stefanvermaas** [comment]
I'm running into the same issue. Did you find a fix for it? 

---

**EDIT:** I've found a way by taking a closer look at the error message...

```docker
# Upgrade RubyGems and install required Bundler version
RUN gem update --system \
  && gem install bundler:$BUNDLER_VERSION \
  && bundle config set force_ruby_platform true
```

Add `bundle config set force_ruby_platform true` to the list of commands for the Gemfile and it will all work just fine.

**Comment by bibendi** [comment]
Please try to use a `bullseye` image. https://hub.docker.com/_/ruby

**Comment by stefanvermaas** [comment]
Oh boy, that worked like charm! Thanks for pointing this out. Thanks @bibendi

**Comment by knight174** [comment]
I encountered this question when I used MacOS to develop my app with ruby 3.0.0 and wanted to deploy it on Linux. 
You can add this command in your Dockerfile:
```
RUN bundle config set force_ruby_platform true
```
And make sure the bundle version in docker is consistent with the version in Gemfile.lock in local. 
If not, add this(my version in local is 2.4.14) into Dockerfile:
```
RUN gem install bundler:2.4.14
```
If you also developed the app by MacOS and deployed it by Linux, you could find a solution at [installing_nokogiri](https://nokogiri.org/tutorials/installing_nokogiri.html#supported-platforms).
Run these commands in development environment:
```
bundle lock --add-platform x86_64-linux
bundle install
```
And try again.
